# Generated by Django 5.2.7 on 2025-10-23 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="title",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
